#!/bin/sh

#*******************************************************************************
#*                                XTpm2Password                                *
#*-----------------------------------------------------------------------------*
#* based on https://github.com/covertsh/ubuntu-autoinstall-generator           *
#*                                                                             *
#* Copyright (c) 2022 Ivan Danov                                               *
#*                                                                             *
#* MIT License                                                                 *
#*                                                                             *
#* Permission is hereby granted, free of charge, to any person obtaining a     *
#* copy of this software and associated documentation files (the "Software"),  *
#* to deal in the Software without restriction, including without limitation   *
#* the rights to use, copy, modify, merge, publish, distribute, sublicense,    *
#* and/or sell copies of the Software, and to permit persons to whom the       *
#* Software is furnished to do so, subject to the following conditions:        *
#*                                                                             *
#* The above copyright notice and this permission notice shall be included     *
#* in all copies or substantial portions of the Software.                      *
#*                                                                             *
#* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS     *
#* OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, *
#* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE *
#* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER      *
#* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING     *
#* FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER         *
#* DEALINGS IN THE SOFTWARE.                                                   *
#*******************************************************************************

set -eu

# SCRIPT_DIR=$(dirname $(realpath ${BASH_SOURCE[0]}))

# NOTE: use same TPM2_INITRAMFS_TOOL_OPTS in xtpm2-password and xtpm2-unseal

# use default "--pcrs 7 --banks SHA256"
TPM2_INITRAMFS_TOOL_OPTS=""
# use custom
#TPM2_INITRAMFS_TOOL_OPTS="--pcrs 0,1,2,3,4,5,6,7 --banks SHA256"

TMP_FILE=".tpm2-getkey.${CRYPTTAB_NAME}.tmp"
if [ -f "${TMP_FILE}" ]; then
	# tmp file exists, meaning we tried the TPM this boot, but it didn’t
	# work for the drive and this must be the second or later pass for the
	# drive. Either the TPM is failed/missing, or has the wrong key stored in it.
	/lib/cryptsetup/askpass "Automatic disk unlock via TPM failed for ($CRYPTTAB_SOURCE) Enter passphrase: "
	exit
fi
# No tmp, so it is the first time trying the script.
# Create a tmp file and try the TPM
touch "${TMP_FILE}"

if key=$(tpm2-initramfs-tool ${TPM2_INITRAMFS_TOOL_OPTS} unseal 2> /dev/null); then
#if [ $? -ne 0 ]; then
	/lib/cryptsetup/askpass "Automatic disk unlock via TPM failed for ($CRYPTTAB_SOURCE) Enter passphrase: "
	exit
fi
printf "%s" "$key"
