#!/bin/bash

#*******************************************************************************
#*                                XTpm2Password                                *
#*-----------------------------------------------------------------------------*
#*                                                                             *
#* Copyright (c) 2022 Ivan Danov                                               *
#*                                                                             *
#* MIT License                                                                 *
#*                                                                             *
#* Permission is hereby granted, free of charge, to any person obtaining a     *
#* copy of this software and associated documentation files (the "Software"),  *
#* to deal in the Software without restriction, including without limitation   *
#* the rights to use, copy, modify, merge, publish, distribute, sublicense,    *
#* and/or sell copies of the Software, and to permit persons to whom the       *
#* Software is furnished to do so, subject to the following conditions:        *
#*                                                                             *
#* The above copyright notice and this permission notice shall be included     *
#* in all copies or substantial portions of the Software.                      *
#*                                                                             *
#* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS     *
#* OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, *
#* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE *
#* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER      *
#* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING     *
#* FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER         *
#* DEALINGS IN THE SOFTWARE.                                                   *
#*******************************************************************************

set -eu

# SCRIPT_DIR=$(dirname $(realpath ${BASH_SOURCE[0]}))

if [[ $EUID -ne 0 ]]; then
	echo "This script must be run as root"
	exit 1
fi

argc=$#
if [ ${argc} -ne 2 ]; then
	echo "Usage:"
	echo "	${0} <old password> <new password>"
	exit 1
fi

function no_ctrlc {
	echo "CTRL-C"
	exit 1
}
function atexit {
	echo "Exit"
}
trap atexit EXIT
trap no_ctrlc SIGINT

if [ ! -f /etc/crypttab ]; then
	echo "No /etc/crypttab"
	exit 1
fi
if [ "$(grep -c luks /etc/crypttab 2>/dev/null|| echo 0)" -le 0 ]; then
	echo "No luks partitions in /etc/crypttab"
	exit 1
fi

OLD_PWD=${1}
NEW_PWD=${2}

CRYPTDISK_UUID="$(grep luks /etc/crypttab|cut -d ' ' -f 2|cut -d '=' -f 2 2>/dev/null)"
if [ -z "${CRYPTDISK+x}" ]; then
	CRYPTDISK="/dev/disk/by-uuid/${CRYPTDISK_UUID}"
	if [ ! -b "${CRYPTDISK}" ]; then
		echo "Cannot find encrypted disk from crypttab"
		exit 1
	fi
fi

# change password in luks from OLD_PWD to NEW_PWD
# NOTE: newPassword.key is on encrypted partition
echo -n "$NEW_PWD" > newPassword.key
echo -n "$OLD_PWD" | cryptsetup luksChangeKey "${CRYPTDISK}" newPassword.key
rm newPassword.key

# set TPM

# NOTE: use same TPM2_INITRAMFS_TOOL_OPTS in xtpm2-password and xtpm2-unseal

# use default "--pcrs 7 --banks SHA256"
TPM2_INITRAMFS_TOOL_OPTS=""
# use custom
#TPM2_INITRAMFS_TOOL_OPTS="--pcrs 0,1,2,3,4,5,6,7 --banks SHA256"

# store passphrase to TPM
# shellcheck disable=SC2086
tpm2-initramfs-tool ${TPM2_INITRAMFS_TOOL_OPTS} seal --data "${NEW_PWD}" > /dev/null

# Add binaries and libraries to initramfs
cat > /etc/initramfs-tools/hooks/xtpm2-password-initramfs-tool <<EOF
. /usr/share/initramfs-tools/hook-functions

copy_exec /usr/lib/x86_64-linux-gnu/libtss2-tcti-device.so.0
copy_exec /usr/bin/tpm2-initramfs-tool
copy_exec /usr/lib/xtpm2-password/xtpm2-unseal
EOF

chmod 755 /etc/initramfs-tools/hooks/xtpm2-password-initramfs-tool


sed -i "/${CRYPTDISK_UUID}/ s/,keyscript=[^, \t]*//" /etc/crypttab
sed -i "/${CRYPTDISK_UUID}/ s/,discard//g" /etc/crypttab
sed -i "/${CRYPTDISK_UUID}/ s/luks/luks,discard,keyscript=\/usr\/lib\/xtpm2-password\/xtpm2-unseal/g" /etc/crypttab

# generate new initramfs
update-initramfs -u

sync
